import Header from '@/components/Header';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next App Route',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className='bg-gray-50'>
        <div
          className='
        bg-slate-200 max-w-7xl mx-auto shadow-xl 
          border-1 min-h-[52rem] border-gray-600'
        >
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
